### ISSUE TITLE
json.meta['record-count']   or json.meta.page['total']  ?

### ISSUE THREAD

**Issue by cyberbizness** [moonlight-labs/aor-jsonapi-client#1]
...

**Comment by cyberbizness** [comment]
More details here : http://jsonapi.org/format/#fetching-pagination

**Comment by cyberbizness** [comment]
And here.. https://github.com/holidayextras/jsonapi-server/blob/master/documentation/configuring.md
I do see :
  // (optional) meta can be a function to be invoked at the end of every request
  meta: function(request) {
    return { timestamp: new Date() };
  }

maybe this is how I could handle custom pagination with that module (?)

**Comment by maxschridde1494** [comment]
Hi Marco, I apologize for my delayed response - just returned from a trip. I will look into this and get back to you within the next 24 hours.

**Comment by marcogadget** [comment]
No problem Max! ;-) It's a pleasure to share ;-) If you need anything else, let me know! I'm currently trying to update the admin-on-rest-demo with the implementation of "jsonapi-server", "jsonapi-mongodb-store" and "aor-jsonapi-client". I can give you a link to my repo later if you need (I need to push my code before)

**Comment by cyberbizness** [comment]
No problem Max! ;-) It's a pleasure to share ;-) If you need anything else, let me know! I'm currently trying to update the admin-on-rest-demo with the implementation of "jsonapi-server", "jsonapi-mongodb-store" and "aor-jsonapi-client". I can give you a link to my repo later if you need (I need to push my code before)

**Comment by cyberbizness** [comment]
Here's the aor demo I did modify to test integration of : 
jsonapi-server, jsonapi-mongodb-store and aor-jsonapi-client

https://github.com/cyberbizness/aor-jsonapi-mongodb-demo/

**Comment by cyberbizness** [comment]
Is it possible to create a Pull Request ? ;-)

**Comment by marcogadget** [comment]
@maxschridde1494

**Comment by cyberbizness** [comment]
@maxschridde1494 ?

**Comment by cyberbizness** [comment]
Like this : https://github.com/practo/aor-jsonapi-client/commit/b1878adb19e66203fd107160e65b878bde1a9050
